version: '3.8'

services:
  mongo_db:
    image: mongo:latest
    ports:
      - "27017:27017"

  redis_cache:
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbitmq_queue:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"